# Generated by Django 2.1.3 on 2018-12-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181211_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deslikes',
            field=models.IntegerField(default=0, verbose_name='Dislike'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Like'),
        ),
    ]
