# Generated by Django 2.1.3 on 2018-12-12 13:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181212_1902'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('activ', django.db.models.manager.Manager()),
            ],
        ),
    ]
