# Generated by Django 2.1.3 on 2018-12-14 10:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181213_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
